[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
startCommand = "gunicorn app:app --bind 0.0.0.0:$PORT --workers 1"

[env]
PORT = "8080"
PYTHONUNBUFFERED = "1"
FLASK_ENV = "production"
